### ISSUE TITLE
Suggest CSS in JS instead of Prebuilded css

### ISSUE THREAD

**Issue by CXZ7720** [BusHanyang/hybus-genesis#14]
I strongly suggest to use CSS-in-JS library instead of pre-builded css sets like Tailwind CSS.

Here's good articles about CSS in JS.
https://d0gf00t.tistory.com/22
https://velog.io/@bepyan/CSS-in-JS-%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC%EC%97%90-%EB%8C%80%ED%95%9C-%EA%B3%A0%EC%B0%B0

### Suggested libraries
* [Vanila Extract](https://vanilla-extract.style/)
* [Stitches](https://stitches.dev/)
* [Linaria](https://linaria.dev)
* [Styled Compoents](https://styled-components.com/)

**Comment by Taewan-P** [comment]
Currently in progress in #15

**Comment by Taewan-P** [comment]
The main release PR #15 is merged now.
CSS in JS is not fully supported yet, but it is applied in many of the components. 
Furthermore, we will migrate to CSS in JS fully step by step.
